steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/git-334002/cloud-arman2:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/git-334002/cloud-arman2:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'git-334002', '--platform=managed', '--allow-unauthenticated', '--region=us-central1', '--image=gcr.io/git-334002/cloud-arman2:$SHORT_SHA']
